### ISSUE TITLE
Doesn't consider default scopes

### ISSUE THREAD

**Issue by dwijnand** [pfn/sbt-unused#2]
**build.properties**

``` ini
sbt.version=0.13.12
```

**project/plugins.sbt**

``` scala
resolvers += Resolver.bintrayIvyRepo("pfn", "sbt-plugins")
addSbtPlugin("com.hanhuy.sbt" % "sbt-unused" % "0.1")
```

**build.sbt**

``` scala
        name := "t"
     version := "0.1.0-SNAPSHOT"
scalaVersion := "2.11.8"

scalacOptions += "-feature"
```

**T.scala**

``` scala
package p

object T {
  val xs = 1 to 10 toList
}
```

```
$ sbt
[info] Loading global plugins from /Users/dnw/.dotfiles/.sbt/0.13/plugins
[info] Loading project definition from /s/t/project
[info] Set current project to t (in build file:/s/t/)
[warn] Unused t/*:initialize defined at /Users/dnw/.sbt/0.13/colour.sbt
[warn] Unused */*:transitiveClassifiers defined at /Users/dnw/.sbt/0.13/nojavadocs.sbt
[warn]   did you mean to use:
[warn]     t/*:updateSbtClassifiers::transitiveClassifiers
[warn]     t/*:updateClassifiers::transitiveClassifiers
[warn] Unused t/*:buildFilesHashes defined at /Users/dnw/.sbt/0.13/reload.sbt
[warn] Unused /*:shellPrompt defined at /Users/dnw/.sbt/0.13/reload.sbt
[warn] Unused t/*:scalacOptions defined at /s/t/build.sbt
[warn]   did you mean to use:
[warn]     t/compile:doc::scalacOptions
[warn]     t/compile:compile::scalacOptions
[warn]     t/compile:console::scalacOptions
[warn]     t/compile:consoleQuick::scalacOptions
[warn]     t/test:doc::scalacOptions
[warn]     t/test:compile::scalacOptions
[warn]     t/test:console::scalacOptions
[warn]     t/test:consoleQuick::scalacOptions
> compile
[info] Updating {file:/s/t/}t...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Compiling 1 Scala source to /s/t/target/scala-2.11/classes...
[warn] /s/t/T.scala:4: postfix operator toList should be enabled
[warn] by making the implicit value scala.language.postfixOps visible.
[warn] This can be achieved by adding the import clause 'import scala.language.postfixOps'
[warn] or by setting the compiler option -language:postfixOps.
[warn] See the Scaladoc for value scala.language.postfixOps for a discussion
[warn] why the feature should be explicitly enabled.
[warn]   val xs = 1 to 10 toList
[warn]                    ^
[warn] one warning found
[success] Total time: 3 s, completed 23-Jul-2016 10:33:18
```

Obviously `scalacOptions += "-feature"` isn't unused, otherwise the compile output would look like:

```
[info] Compiling 1 Scala source to /s/t/target/scala-2.11/classes...
[warn] there was one feature warning; re-run with -feature for details
[warn] one warning found
```

Also, the other warnings are coming from various bits-and-bobs in my global plugins, all that work as well.

**Comment by paulp** [comment]
This plugin would be way more useful if this were fixed. It's a fantastic idea but even if I act like default scopes don't exist and be very explicit about everything, it still issues spurious warnings which I can't eliminate for such keys as `initialize` and `shellPrompt`.

**Comment by pfn** [comment]
Yeah, I've been thinking about how this can be solved reasonably. Eg if
scalacOptions in Compile were already set and a naked scalacOptions were
later set, the behavior would be unexpected (no warning, but setting not
applied to intended scope)

**Comment by paulp** [comment]
As an aside, you are the only other person I've ever heard articulate that the biggest problem with sbt is its callous disregard for whether your settings make any sense whatsoever (nb "I believe setting scope errors are the number 1 reason why SBT is considered hard to use and mystical") so I applaud this awareness. I feel like it is in the category of problems which people for the most part literally cannot conceptualize, no matter how much they suffer for it: it's as if they accept sbt as part of nature, unchangeable by man, and this is simply how things must be.

**Comment by dwijnand** [comment]
I also think something could be done with your settings.dump idea (https://github.com/paulp/policy/commit/df024d5d350bc7e6e22cd3a479132e6b58f6ee52#diff-fdc3abdfd754eeb24090dbd90aeec2ceL7).

I'm not sure exactly what shape it should have, but I think it's something that should exist, in the same vein as this plugin.

**Comment by paulp** [comment]
Heh, I was going to mention that but I couldn't remember where I left it.

**Comment by pfn** [comment]
So, I have an idea that may work for handling default settings:
1. For every unreferenced setting, see if there are any references to more specific instances of said setting (for default fall back).
   - if there are no references to a more specific instance, it is marked as unreferenced and warned
2. For every instance that satisfies the above, check to see if there are any settings definitions that occur "between" the reference and the configured value.
   - if there is a more specific setting that satisfies the reference, warn that the setting may be unused
   - the reasoning is: "If I have `scalaOptions in Compile` configured, when I later set a naked `scalaOptions := ...`, I probably did it wrong." This will still issue a warning if this is intentional however, e.g. one set specific options for `scalaOptions in Test` and want to use defaults for everything else; I don't know what to do for this case yet.

Now to consider how this would be written...

**Comment by paulp** [comment]
@pfn I think it's fine if using `:=`always generates a warning where things look sketchy, because it ought to mean something like "set unitialized key to value foo." If you set `scalacOptions :=` after setting `scalacOptions in Compile :=` then you have invalidated the attempt to set `scalacOptions in Compile` with `:=` because it is no longer an uninitialized key.

In other words, you have to map setting values to new values, not abruptly set them to constant values. 

When mapping a setting value you can always discard the input, so you can still abruptly set them to fixed values: but you have to explicitly discard the previous value, and that is the point.

**Comment by paulp** [comment]
So`key := value` should be seen like

```
key mapPreviousValue { case None => value ; case Some(_) => fail() }
```

**Comment by dwijnand** [comment]
@pfn Relevant to your efforts here: https://github.com/sbt/sbt/issues/1815#issuecomment-70548307
